jobs:
  build:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/chrisvanlawdotcom
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $CIRCLE_PROJECT_USERNAME/chrisvanlawdotcom
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
orbs:
  docker: circleci/docker@0.5.21
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - build