name: 'Build & Push Container Image'
on:
  push:
    branchs:
      - main
  pull_request:
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '100'
      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
      - name: Login to Docker
        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build docker image
        run: docker build . --tag cvanlaw/chrisvanlawcom:latest --tag cvanlaw/chrisvanlawcom:${{ steps.semver.outputs.new_tag }}
      - name: Push docker image
        run: docker push cvanlaw/chrisvanlawcom:${{ steps.semver.outputs.new_tag }} && docker push cvanlaw/chrisvanlawcom:latest
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}