name: 'Website'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '100'
      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install jekyll bundler
      - name: Build
        id: build
        working-directory: src
        run: |
          bundle install
          bundle exec jekyll build
      - name: Upload Build Artifact
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v3
        with:
          name: build_assets
          path: src/_site
  deploy:
    name: 'Deploy'
    needs: build
    runs-on: ubuntu-20.04
    if: github.ref_name == 'main'
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build_assets
          path: build_assets
      - name: Upload to S3 Bucket and Refresh Cloudfront
        working-directory: build_assets
        run: |
          aws s3 sync . s3://$BUCKET_NAME --metadata-directive 'REPLACE'
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}