name: 'Build & Push Container Image'
on:
  push:
    branchs:
      - main
  pull_request:

env:
  BUCKET_NAME: "chrisvanlaw.com"
  DISTRIBUTION_ID: "E3UKNMTEMHSZAC"

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '100'
      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install jekyll bundler
      - name: Build
        id: build
        working-directory: src
        run: |
          bundle install
          bundle exec jekyll build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site_assets
          path: ./_site


        # - bash: aws s3 sync . s3://$BUCKET_NAME --metadata-directive 'REPLACE' && aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html
        #     displayName: Deploy UI to S3
        #     workingDirectory: '$(Pipeline.Workspace)/sp_ng_ui'
        #     env:
        #       AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        #       AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        #       BUCKET_NAME: $(PRODUCTION_UI_BUCKET_NAME)
        #       AWS_REGION: us-east-1
        #       DISTRIBUTION_ID: $(PRODUCTION_DISTRIBUTION_ID)