name: 'Build & Push Container Image'
on:
  push:
    branchs:
      - main
  pull_request:
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: test
        run: echo ${{ steps.semver.outputs.new_tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: cvanlaw/chrisvanlawcom:latest,cvanlaw/chrisvanlawcom:${{ steps.semver.outputs.new_tag }}